/**
 * ECE — Electronics and Communication Engineering Mock Questions
 * GATE pattern-based original questions
 */

export function generateECE(mock: string): any[] {
  const base = mock === 'mock1' ? 'High-probability standard' :
               mock === 'mock2' ? 'Trend + application' : 'Predicted challenge';

  return [
    // Network Theory
    { id: `ece_${mock}_q01`, type: 'mcq', subject: 'Network Theory', marks: 1, difficulty: 'easy',
      question: 'According to Thevenin\'s theorem, any linear network can be replaced by a voltage source and a:',
      options: ['Resistor', 'Current source', 'Inductor', 'Capacitor'], answer: 'A' },
    { id: `ece_${mock}_q02`, type: 'mcq', subject: 'Network Theory', marks: 2, difficulty: 'moderate',
      question: 'In the Laplace domain, the impedance of an inductor L=1H is:',
      options: ['1/s', 's', '1/(sL)', 'sL'], answer: 'D' },
    { id: `ece_${mock}_q03`, type: 'nat', subject: 'Network Theory', marks: 2, difficulty: 'hard',
      question: 'A 3-phase balanced load draws 10A per phase at 0.8 pf lagging. What is the total real power (P) in kW at 415V?',
      answer: '5744' },
    // Signals & Systems
    { id: `ece_${mock}_q04`, type: 'mcq', subject: 'Signals & Systems', marks: 1, difficulty: 'easy',
      question: 'The Fourier transform of a unit step function u(t) is:',
      options: ['2πδ(ω)', 'πδ(ω) + 1/jω', '1/jω', 'jω'], answer: 'B' },
    { id: `ece_${mock}_q05`, type: 'nat', subject: 'Signals & Systems', marks: 2, difficulty: 'moderate',
      question: 'A signal x(t) = e^(-2t)u(t) has Laplace transform X(s). What is the ROC?',
      answer: '2' },
    { id: `ece_${mock}_q06`, type: 'msq', subject: 'Signals & Systems', marks: 2, difficulty: 'hard',
      question: 'Which of the following systems are LTI? (Select all that apply)',
      options: ['y(t) = x(t-1)', 'y(t) = tx(t)', 'y(t) = x(t²)', 'y[n] = 2x[n]', 'y[n] = x[n] + 1'], answer: ['A', 'D'] },
    // Control Systems
    { id: `ece_${mock}_q07`, type: 'mcq', subject: 'Control Systems', marks: 2, difficulty: 'moderate',
      question: 'The transfer function of a system with characteristic equation s³ + 3s² + 2s + 1 = 0. Using Routh-Hurwitz, how many roots have positive real parts?',
      options: ['0', '1', '2', '3'], answer: 'A' },
    { id: `ece_${mock}_q08`, type: 'nat', subject: 'Control Systems', marks: 2, difficulty: 'hard',
      question: 'For a unity feedback system with G(s) = K/(s(s+2)), what is the value of K for marginal stability (gain margin = 0 dB)?',
      answer: '4' },
    // Digital Electronics
    { id: `ece_${mock}_q09`, type: 'mcq', subject: 'Digital Electronics', marks: 1, difficulty: 'easy',
      question: 'A 4-bit shift register shifts left on each clock. After 4 clocks, the input 1011 produces output:',
      options: ['1011', '1110', '0000', '0111'], answer: 'A' },
    { id: `ece_${mock}_q10`, type: 'mcq', subject: 'Digital Electronics', marks: 2, difficulty: 'moderate',
      question: 'The propagation delay of a 4-input NAND gate with t_pd=5ns. What is the maximum frequency of operation?',
      options: ['100 MHz', '200 MHz', '50 MHz', '25 MHz'], answer: 'B' },
    // Analog Circuits
    { id: `ece_${mock}_q11`, type: 'mcq', subject: 'Analog Circuits', marks: 2, difficulty: 'moderate',
      question: 'In an ideal op-amp integrator with R=10kΩ and C=1μF, the output for a unit step input (1V) is:',
      options: ['Constant', 'Ramp', 'Parabola', 'Zero'], answer: 'B' },
    { id: `ece_${mock}_q12`, type: 'nat', subject: 'Analog Circuits', marks: 2, difficulty: 'hard',
      question: 'A CE amplifier with β=100, R_C=5kΩ, R_E=1kΩ has voltage gain approximately: (Answer: gain in V/V)',
      answer: '500' },
    // EMFT
    { id: `ece_${mock}_q13`, type: 'mcq', subject: 'EMFT', marks: 2, difficulty: 'moderate',
      question: 'The intrinsic impedance of free space η₀ is approximately:',
      options: ['50Ω', '120π Ω', '377Ω', 'Both B and C'], answer: 'D' },
    { id: `ece_${mock}_q14`, type: 'nat', subject: 'EMFT', marks: 2, difficulty: 'hard',
      question: 'A parallel plate capacitor with area 0.1 m² and separation 1mm has capacitance in pF: (ε₀=8.85×10⁻¹² F/m)',
      answer: '885' },
    // Communication Systems
    { id: `ece_${mock}_q15`, type: 'mcq', subject: 'Communication Systems', marks: 2, difficulty: 'moderate',
      question: 'In AM modulation, the modulation index μ must be:',
      options: ['μ > 1', 'μ = 1', 'μ ≤ 1', 'μ = 0'], answer: 'C' },
    { id: `ece_${mock}_q16`, type: 'nat', subject: 'Communication Systems', marks: 2, difficulty: 'hard',
      question: 'An FM signal with frequency deviation 75kHz and modulating frequency 15kHz has modulation index β = ?',
      answer: '5' },
    // Microprocessors
    { id: `ece_${mock}_q17`, type: 'mcq', subject: 'Microprocessors', marks: 1, difficulty: 'easy',
      question: 'The 8085 microprocessor has how many address lines?',
      options: ['8', '16', '20', '32'], answer: 'B' },
    { id: `ece_${mock}_q18`, type: 'nat', subject: 'Microprocessors', marks: 2, difficulty: 'moderate',
      question: 'In 8085, what is the maximum memory that can be interfaced? (Answer in KB)',
      answer: '64' },
    // EDC
    { id: `ece_${mock}_q19`, type: 'mcq', subject: 'EDC', marks: 1, difficulty: 'easy',
      question: 'The most commonly used IC voltage regulator series is:',
      options: ['LM78XX', 'LM317', 'LM741', '555 Timer'], answer: 'A' },
    { id: `ece_${mock}_q20`, type: 'mcq', subject: 'EDC', marks: 2, difficulty: 'moderate',
      question: 'In a half-wave rectifier with input 12Vrms, the peak output voltage (ideal diode) is approximately:',
      options: ['5.4V', '12V', '17V', '6V'], answer: 'C' },
    // Maths
    { id: `ece_${mock}_q21`, type: 'mcq', subject: 'Engineering Mathematics', marks: 1, difficulty: 'easy',
      question: 'The inverse Laplace transform of 1/(s+2) is:',
      options: ['e^(-2t)', 'e^(2t)', '2e^(-2t)', 'te^(-2t)'], answer: 'A' },
    { id: `ece_${mock}_q22`, type: 'nat', subject: 'Engineering Mathematics', marks: 2, difficulty: 'moderate',
      question: 'If A is a 3×3 matrix with eigenvalues 1, 2, 3, what is the trace of A²?',
      answer: '14' },
    { id: `ece_${mock}_q23`, type: 'mcq', subject: 'Network Theory', marks: 2, difficulty: 'hard',
      question: 'In a balanced 3-phase Y-connected load with impedance Z=6+j8Ω, what is the power factor?',
      options: ['0.6 lag', '0.8 lag', '0.6 lead', '0.8 lead'], answer: 'A' },
    { id: `ece_${mock}_q24`, type: 'msq', subject: 'Control Systems', marks: 2, difficulty: 'hard',
      question: 'Which of the following improve steady-state error? (Select all that apply)',
      options: ['Increasing Kp', 'Adding integral control', 'Adding derivative control', 'Adding a lag compensator', 'Adding a lead compensator'], answer: ['A', 'B', 'D'] },
    { id: `ece_${mock}_q25`, type: 'mcq', subject: 'Digital Electronics', marks: 2, difficulty: 'hard',
      question: 'How many flip-flops are needed to design a modulo-16 counter?',
      options: ['2', '3', '4', '16'], answer: 'C' },
    { id: `ece_${mock}_q26`, type: 'nat', subject: 'Signals & Systems', marks: 2, difficulty: 'moderate',
      question: 'A periodic signal has Fourier series coefficients. If ω₀=2π, what is the fundamental frequency in rad/s?',
      answer: '2' },
    { id: `ece_${mock}_q27`, type: 'mcq', subject: 'Communication Systems', marks: 2, difficulty: 'hard',
      question: 'The Shannon-Hartley theorem states that channel capacity C =:',
      options: ['B log₂(1+S/N)', 'B log₁₀(1+S/N)', 'S/N × log₂(B)', '2B log₂(1+S/N)'], answer: 'A' },
    { id: `ece_${mock}_q28`, type: 'mcq', subject: 'EMFT', marks: 2, difficulty: 'moderate',
      question: 'The skin depth δ is proportional to:',
      options: ['√σ', '1/√σ', '1/σ', '√f'], answer: 'B' },
    { id: `ece_${mock}_q29`, type: 'mcq', subject: 'Analog Circuits', marks: 1, difficulty: 'easy',
      question: 'The input impedance of an ideal op-amp is:',
      options: ['Zero', 'Infinite', 'Equal to output impedance', '1MΩ'], answer: 'B' },
    { id: `ece_${mock}_q30`, type: 'nat', subject: 'Network Theory', marks: 2, difficulty: 'hard',
      question: 'For a two-port network with Y-parameters Y₁₁=2S, Y₁₂=Y₂₁=-0.5S, Y₂₂=3S, the transmission parameter A = ?',
      answer: '3' },
    // Additional questions to reach 60
    { id: `ece_${mock}_q31`, type: 'mcq', subject: 'Microprocessors', marks: 2, difficulty: 'moderate',
      question: 'The 8051 microcontroller has how many I/O ports?',
      options: ['2', '4', '8', '16'], answer: 'B' },
    { id: `ece_${mock}_q32`, type: 'nat', subject: 'EDC', marks: 2, difficulty: 'moderate',
      question: 'A Zener diode with Vz=5.1V and Rz=5Ω has load regulation in mV/mA:',
      answer: '5' },
    { id: `ece_${mock}_q33`, type: 'mcq', subject: 'Digital Electronics', marks: 2, difficulty: 'hard',
      question: 'A 4-bit DAC with Vref=5V has resolution of:',
      options: ['0.3125V', '0.625V', '0.5V', '1.25V'], answer: 'A' },
    { id: `ece_${mock}_q34`, type: 'mcq', subject: 'Control Systems', marks: 2, difficulty: 'hard',
      question: 'For a system with open-loop TF G(s)=1/(s(s+1)), the type number is:',
      options: ['0', '1', '2', '3'], answer: 'B' },
    { id: `ece_${mock}_q35`, type: 'msq', subject: 'Communication Systems', marks: 2, difficulty: 'hard',
      question: 'Which of the following are digital modulation schemes? (Select all that apply)',
      options: ['ASK', 'FSK', 'PSK', 'AM', 'QAM'], answer: ['A', 'B', 'C', 'E'] },
    { id: `ece_${mock}_q36`, type: 'mcq', subject: 'Engineering Mathematics', marks: 2, difficulty: 'moderate',
      question: 'If Z₁=3+4j and Z₂=1-2j, then Z₁/Z₂ =:',
      options: ['-1+2j', '1.4+2j', '2-3j', '-1+4j'], answer: 'A' },
    { id: `ece_${mock}_q37`, type: 'nat', subject: 'Signals & Systems', marks: 2, difficulty: 'hard',
      question: 'A system has impulse response h(t) = e^(-3t)u(t). What is its DC gain (at s=0)?',
      answer: '1' },
    { id: `ece_${mock}_q38`, type: 'mcq', subject: 'Network Theory', marks: 2, difficulty: 'hard',
      question: 'In a 3-phase circuit, two wattmeters read 500W and 100W respectively (with wattmeter A leading). What is the total power?',
      options: ['400W', '600W', '700W', 'Cannot be determined'], answer: 'B' },
    { id: `ece_${mock}_q39`, type: 'mcq', subject: 'EMFT', marks: 2, difficulty: 'moderate',
      question: 'The divergence of the electric field E in free space is given by:',
      options: ['ρ/ε₀', '0', '-∂B/∂t', 'μ₀J'], answer: 'A' },
    { id: `ece_${mock}_q40`, type: 'nat', subject: 'Analog Circuits', marks: 2, difficulty: 'hard',
      question: 'In a common collector amplifier (emitter follower), the voltage gain is typically approximately:',
      answer: '1' },
    { id: `ece_${mock}_q41`, type: 'mcq', subject: 'Digital Electronics', marks: 2, difficulty: 'moderate',
      question: 'A 4-bit Johnson counter divides the clock frequency by a factor of:',
      options: ['4', '6', '8', '16'], answer: 'C' },
    { id: `ece_${mock}_q42`, type: 'mcq', subject: 'Communication Systems', marks: 2, difficulty: 'hard',
      question: 'The noise figure (NF) of a noiseless amplifier is:',
      options: ['0 dB', '1 dB', '3 dB', '0'], answer: 'A' },
    { id: `ece_${mock}_q43`, type: 'nat', subject: 'Control Systems', marks: 2, difficulty: 'moderate',
      question: 'For G(s) = 1/(s(s+3)(s+6)), the number of asymptotes in root locus is:',
      answer: '3' },
    { id: `ece_${mock}_q44`, type: 'mcq', subject: 'EDC', marks: 2, difficulty: 'hard',
      question: 'In a negative feedback amplifier with A=1000 and β=0.01, the closed-loop gain is approximately:',
      options: ['1000', '100', '10', '0.01'], answer: 'C' },
    { id: `ece_${mock}_q45`, type: 'mcq', subject: 'Network Theory', marks: 2, difficulty: 'moderate',
      question: 'The power factor of an RLC circuit at resonance is:',
      options: ['0', '0.5', '1', 'Depends on values'], answer: 'C' },
    { id: `ece_${mock}_q46`, type: 'mcq', subject: 'Signals & Systems', marks: 2, difficulty: 'hard',
      question: 'If x(t) has Fourier transform X(ω), then X(ω) at ω=0 gives:',
      options: ['Energy', 'Power', 'DC component (integral)', 'Average power'], answer: 'C' },
    { id: `ece_${mock}_q47`, type: 'nat', subject: 'Microprocessors', marks: 2, difficulty: 'moderate',
      question: 'The 8085 microprocessor executes INR A in how many T-states?',
      answer: '4' },
    { id: `ece_${mock}_q48`, type: 'msq', subject: 'Digital Electronics', marks: 2, difficulty: 'hard',
      question: 'Which of the following are synchronous sequential circuits? (Select all that apply)',
      options: ['Flip-flop', 'Shift register', 'Combinational decoder', 'Counter', 'Multiplexer'], answer: ['A', 'B', 'D'] },
    { id: `ece_${mock}_q49`, type: 'mcq', subject: 'Analog Circuits', marks: 2, difficulty: 'moderate',
      question: 'In a differential amplifier with CMRR=80dB and differential gain=100, the common-mode gain is approximately:',
      options: ['10', '1', '0.01', '1000'], answer: 'C' },
    { id: `ece_${mock}_q50`, type: 'mcq', subject: 'Engineering Mathematics', marks: 2, difficulty: 'hard',
      question: 'A random variable X follows uniform distribution U[0,4]. What is Var(X)?',
      options: ['4/3', '16/3', '4', '2'], answer: 'A' },
    { id: `ece_${mock}_q51`, type: 'nat', subject: 'Network Theory', marks: 2, difficulty: 'hard',
      question: 'In a series RLC circuit with R=10Ω, L=1H, C=0.01F, the resonant frequency in rad/s is:',
      answer: '10' },
    { id: `ece_${mock}_q52`, type: 'mcq', subject: 'Control Systems', marks: 2, difficulty: 'moderate',
      question: 'A system is BIBO stable if:',
      options: ['All poles are on imaginary axis', 'All poles are in left half-plane', 'All zeros are in LHP', 'Gain is finite'], answer: 'B' },
    { id: `ece_${mock}_q53`, type: 'mcq', subject: 'Communication Systems', marks: 2, difficulty: 'moderate',
      question: 'DSB-SC modulation requires:',
      options: ['Square-law device', 'Product modulator', 'Envelope detector', 'Limiter'], answer: 'B' },
    { id: `ece_${mock}_q54`, type: 'nat', subject: 'EMFT', marks: 2, difficulty: 'hard',
      question: 'For a rectangular waveguide operating in TE₁₀ mode with a=2cm, b=1cm, the cutoff frequency in GHz is: (c=3×10⁸ m/s)',
      answer: '7.5' },
    { id: `ece_${mock}_q55`, type: 'mcq', subject: 'Digital Electronics', marks: 2, difficulty: 'hard',
      question: 'A ROM with 8 address lines and 4 data lines has how many bits of storage?',
      options: ['32 bits', '128 bits', '256 bits', '1024 bits'], answer: 'D' },
    { id: `ece_${mock}_q56`, type: 'mcq', subject: 'Signals & Systems', marks: 2, difficulty: 'moderate',
      question: 'The ROC of the Z-transform of a right-sided sequence x[n] = aⁿ u[n] (|a|<1) is:',
      options: ['|z| > |a|', '|z| < |a|', '|z| = |a|', 'Entire z-plane'], answer: 'A' },
    { id: `ece_${mock}_q57`, type: 'mcq', subject: 'EDC', marks: 1, difficulty: 'easy',
      question: 'A BJT in active region has which junction forward biased and which reverse biased?',
      options: ['EB forward, CB forward', 'EB forward, CB reverse', 'EB reverse, CB forward', 'Both reverse'], answer: 'B' },
    { id: `ece_${mock}_q58`, type: 'nat', subject: 'Analog Circuits', marks: 2, difficulty: 'moderate',
      question: 'An ideal op-amp in negative feedback with R_f=10kΩ and R_in=2kΩ has gain = ?',
      answer: '-5' },
    { id: `ece_${mock}_q59`, type: 'mcq', subject: 'Microprocessors', marks: 2, difficulty: 'hard',
      question: 'In 8085, the instruction LDA addr (3 bytes) takes how many machine cycles?',
      options: ['1', '2', '3', '4'], answer: 'D' },
    { id: `ece_${mock}_q60`, type: 'mcq', subject: 'Engineering Mathematics', marks: 2, difficulty: 'hard',
      question: 'The solution to dy/dx = y with y(0)=1 is:',
      options: ['y = e^x', 'y = x+1', 'y = 1/x', 'y = x²+1'], answer: 'A' },
  ];
}

export function generateEE(mock: string): any[] {
  return generateECE(mock).map((q, i) => ({
    ...q,
    id: q.id.replace('ece', 'ee'),
    subject: mapSubject(q.subject, 'ece', 'ee'),
  }));
}

function mapSubject(s: string, from: string, to: string): string {
  const map: Record<string, Record<string, string>> = {
    ece: {
      'Network Theory': 'Network Theory',
      'Signals & Systems': 'Signals & Systems',
      'Control Systems': 'Control Systems',
      'Digital Electronics': 'Digital Electronics',
      'Analog Circuits': 'Analog Electronics',
      'EMFT': 'EMFT',
      'Communication Systems': 'Communication Systems',
      'Microprocessors': 'Microprocessors',
      'EDC': 'Electronic Devices',
      'Engineering Mathematics': 'Engineering Mathematics',
    },
    ee: {
      'Network Theory': 'Network Theory',
      'Signals & Systems': 'Signals & Systems',
      'Control Systems': 'Control Systems',
      'Digital Electronics': 'Digital Electronics',
      'Analog Electronics': 'Analog Electronics',
      'EMFT': 'EMFT',
      'Communication Systems': 'Communication Systems',
      'Microprocessors': 'Microprocessors',
      'Electronic Devices': 'Electronic Devices',
      'Engineering Mathematics': 'Engineering Mathematics',
      'Electrical Machines': 'Electrical Machines',
      'Power Systems': 'Power Systems',
      'Power Electronics': 'Power Electronics',
      'Measurements': 'Measurements',
    },
  };
  return map[from]?.[s] || s;
}
