/**
 * PDF Renderer — generates professionally formatted mock test PDFs using pdfkit.
 *
 * Each paper includes:
 *   - Cover page with EduNeuro branding
 *   - General instructions
 *   - Section-wise questions (MCQ/MSQ/NAT) in one continuous paper
 *   - Answer key
 *   - Detailed solutions
 *   - EduNeuro watermark on every page
 */

import PDFDocument from 'pdfkit';
import * as fs from 'fs';
import * as path from 'path';
import { Question, PaperMetadata, BRANCHES, ROOT } from './__config';

const FONT_REGULAR = 'Helvetica';
const FONT_BOLD = 'Helvetica-Bold';
const FONT_ITALIC = 'Helvetica-Oblique';
const PAGE_W = 595.28;  // A4
const PAGE_H = 841.89;
const MARGIN = 55;
const CONTENT_W = PAGE_W - 2 * MARGIN;
const USABLE_H = PAGE_H - 120;

let doc: PDFDocument;
let pageNum = 0;
let globalQNum = 0;

// ── Helpers ────────────────────────────────────────────────────────────────
function addWatermark(text = 'EduNeuro') {
  doc.save();
  doc.fontSize(80).font(FONT_BOLD).fillColor('rgba(0,0,0,0.035)');
  doc.rotate(35, { origin: [PAGE_W / 2, PAGE_H / 2] });
  doc.text(text, PAGE_W / 2 - 150, PAGE_H / 2 - 40);
  doc.restore();
}

function newPage() {
  doc.addPage();
  pageNum++;
  addWatermark();
}

function header(text: string) {
  doc.fontSize(8).font(FONT_ITALIC).fillColor('#999999').text(text, MARGIN, 25, { align: 'center' });
}

function footer() {
  const y = PAGE_H - 25;
  doc.fontSize(8).font(FONT_ITALIC).fillColor('#aaaaaa');
  doc.text('EduNeuro — Premium Full-Length Mock Test | For Premium Users Only', MARGIN, y, { align: 'center' });
  doc.text(`Page ${pageNum}`, PAGE_W - MARGIN - 50, y, { align: 'right' });
}

function drawLine(x1: number, y1: number, x2: number, y2: number, color = '#e7e5e4') {
  doc.moveTo(x1, y1).lineTo(x2, y2).stroke(color);
}

// ── Cover Page ─────────────────────────────────────────────────────────────
function renderCover(meta: PaperMetadata) {
  pageNum = 0;
  addWatermark();

  // Top accent bar
  doc.rect(0, 0, PAGE_W, 6).fill('#d97706');
  doc.rect(0, 6, PAGE_W, 3).fill('#f59e0b');

  // Logo area
  doc.roundedRect(MARGIN, 45, 90, 90, 8).fill('#d97706');
  doc.fontSize(9).font(FONT_BOLD).fillColor('#ffffff').text('EduNeuro', MARGIN + 10, 90, { align: 'center' });

  // Main title
  doc.fontSize(34).font(FONT_BOLD).fillColor('#1c1917').text('PREMIUM', MARGIN, 155);
  doc.fontSize(28).font(FONT_BOLD).fillColor('#d97706').text('Full-Length Mock Test', MARGIN, 195);

  // Mock badge
  const badgeText = `Mock ${String(meta.mock_number).padStart(2, '0')}`;
  const badgeW = badgeText.length * 12 + 30;
  doc.roundedRect(MARGIN, 245, badgeW, 36, 6).fill('#1c1917');
  doc.fontSize(13).font(FONT_BOLD).fillColor('#ffffff').text(badgeText, MARGIN + 15, 257);

  // Branch name
  doc.fontSize(16).font(FONT_BOLD).fillColor('#1c1917').text(meta.branch_name, MARGIN, 305);
  doc.fontSize(13).font(FONT_ITALIC).fillColor('#78716c').text(`GATE ${meta.branch_code}`, MARGIN, 332);

  // Divider
  drawLine(MARGIN, 370, PAGE_W - MARGIN, 370, '#e7e5e4');

  // Details table
  const details = [
    ['Total Questions', String(meta.question_count)],
    ['Maximum Marks', String(meta.maximum_marks)],
    ['Duration', `${meta.duration_minutes} minutes (3 Hours)`],
    ['Exam Pattern', 'MCQ + MSQ + NAT'],
    ['Negative Marking', 'MCQ/MSQ: -0.33 per wrong answer'],
    ['Designed For', 'EduNeuro Premium'],
  ];

  let y = 390;
  for (const [label, value] of details) {
    const labelW = 150;
    doc.fontSize(11).font(FONT_BOLD).fillColor('#44403c').text(label, MARGIN, y, { width: labelW });
    doc.font(FONT_REGULAR).fillColor('#1c1917').text(value, MARGIN + labelW + 5, y);
    y += 26;
  }

  // Difficulty bar
  y += 15;
  const easy = meta.difficulty_distribution.easy;
  const moderate = meta.difficulty_distribution.moderate;
  const hard = meta.difficulty_distribution.hard;
  const barW = CONTENT_W;
  doc.rect(MARGIN, y, barW, 14).fill('#fafaf9').stroke('#e7e5e4');
  doc.rect(MARGIN, y, barW * easy / 100, 14).fill('#10b981');
  doc.rect(MARGIN + barW * easy / 100, y, barW * moderate / 100, 14).fill('#f59e0b');
  doc.rect(MARGIN + barW * (easy + moderate) / 100, y, barW * hard / 100, 14).fill('#ef4444');
  doc.fontSize(8).font(FONT_BOLD).fillColor('#ffffff');
  doc.text(`Easy ${easy}%`, MARGIN + 5, y + 3);
  doc.text(`Moderate ${moderate}%`, MARGIN + barW * easy / 100 + 5, y + 3);
  doc.text(`Hard ${hard}%`, MARGIN + barW * (easy + moderate) / 100 + 5, y + 3);

  // Bottom text
  doc.fontSize(8).font(FONT_ITALIC).fillColor('#a8a29e').text(
    'Based on Previous Year Question Pattern Analysis | Generated by EduNeuro Premium',
    MARGIN, y + 30, { align: 'center', width: CONTENT_W }
  );

  addWatermark();
}

// ── Instructions Page ──────────────────────────────────────────────────────
function renderInstructions() {
  newPage();
  header('General Instructions');

  doc.fontSize(15).font(FONT_BOLD).fillColor('#1c1917').text('General Instructions', MARGIN, 50, { align: 'center' });
  drawLine(MARGIN, 70, PAGE_W - MARGIN, 70, '#e7e5e4');

  const instructions = [
    'This question paper contains THREE sections: Section A, Section B, and Section C.',
    'Section A: Multiple Choice Questions (MCQ) — carries one or two marks each. Only ONE option is correct.',
    'Section B: Multiple Select Questions (MSQ) — carries two marks each. ONE OR MORE than one option(s) is/are correct.',
    'Section C: Numerical Answer Type (NAT) — carries one or two marks. Enter the numerical value in the space provided.',
    'Negative Marking: -0.33 marks will be deducted for each wrong MCQ and each wrong MSQ answer.',
    'No negative marking for NAT questions.',
    'There are 60 questions for a total of 100 marks.',
    'Duration: 3 hours (180 minutes).',
    'Use the space provided for rough work. Scribbling on the question paper is permitted.',
    'Do not ask for clarification from the invigilator. Interpret questions as given.',
  ];

  let y = 85;
  for (const inst of instructions) {
    doc.fontSize(10).font(FONT_REGULAR).fillColor('#1c1917');
    const h = doc.heightOfString(inst, { width: CONTENT_W, lineGap: 4 });
    doc.text(inst, MARGIN, y, { width: CONTENT_W, lineGap: 4 });
    y += h + 10;
  }

  // Section summary
  y += 20;
  doc.fontSize(13).font(FONT_BOLD).fillColor('#1c1917').text('Paper Structure', MARGIN, y);
  y += 22;

  const tableData = [
    ['Section', 'Type', 'Questions', 'Marks/Q', 'Total Marks', 'Negative'],
    ['A', 'MCQ', '35', '1 / 2', '55', '-0.33'],
    ['B', 'MSQ', '5', '2', '10', '-0.33'],
    ['C', 'NAT', '20', '1 / 2', '35', 'None'],
    ['Total', '', '60', '', '100', ''],
  ];

  const colWidths = [55, 70, 80, 75, 85, 110];
  const rowH = 18;
  const tableW = colWidths.reduce((a, b) => a + b, 0);

  // Header
  doc.rect(MARGIN, y, tableW, rowH).fill('#d97706');
  let x = MARGIN;
  for (let c = 0; c < tableData[0].length; c++) {
    doc.fontSize(9).font(FONT_BOLD).fillColor('#ffffff')
      .text(tableData[0][c], x + 3, y + 4, { width: colWidths[c] - 6 });
    x += colWidths[c];
  }
  y += rowH;

  // Rows
  for (let r = 1; r < tableData.length; r++) {
    if (r % 2 === 0) doc.rect(MARGIN, y, tableW, rowH).fill('#fafaf9');
    x = MARGIN;
    for (let c = 0; c < tableData[r].length; c++) {
      const isTotal = r === tableData.length - 1;
      doc.fontSize(9).font(isTotal ? FONT_BOLD : FONT_REGULAR)
        .fillColor(isTotal ? '#1c1917' : '#44403c')
        .text(tableData[r][c], x + 3, y + 4, { width: colWidths[c] - 6 });
      x += colWidths[c];
    }
    y += rowH;
  }

  // Marking formula
  y += 30;
  doc.fontSize(12).font(FONT_BOLD).fillColor('#1c1917').text('Marking Scheme', MARGIN, y);
  y += 20;
  const formulas = [
    'Correct MCQ: +1 mark (or +2 marks as specified per question)',
    'Wrong MCQ: -0.33 marks',
    'Correct MSQ: +2 marks',
    'Wrong MSQ (partial or no match): -0.33 marks',
    'Correct NAT: +1 mark (or +2 marks as specified per question)',
    'No answer / Unattempted: 0 marks',
    'NAT wrong answer: 0 marks (no negative marking)',
  ];
  for (const f of formulas) {
    doc.fontSize(10).font(FONT_REGULAR).fillColor('#44403c').text(f, MARGIN + 10, y, { width: CONTENT_W - 10 });
    y += 16;
  }

  footer();
}

// ── Questions ──────────────────────────────────────────────────────────────
function renderQuestions(sectionTitle: string, questions: Question[], sectionType: string) {
  newPage();
  header(sectionTitle);

  doc.fontSize(13).font(FONT_BOLD).fillColor('#1c1917').text(sectionTitle, MARGIN, 45, { align: 'center' });
  drawLine(MARGIN, 62, PAGE_W - MARGIN, 62, '#e7e5e4');

  let y = 72;

  for (const q of questions) {
    const qNum = q.id.split('_q')[1];
    globalQNum++;

    // Question number + marks + difficulty
    const headerText = `Q.${qNum}   [${q.marks} Mark${q.marks > 1 ? 's' : ''}]   [${q.difficulty.toUpperCase()}]   [${q.subject} — ${q.topic}]`;
    doc.fontSize(9).font(FONT_BOLD).fillColor('#d97706').text(headerText, MARGIN, y);
    y += 15;

    // Question text
    doc.fontSize(10).font(FONT_REGULAR).fillColor('#1c1917');
    const qTextH = doc.heightOfString(q.question, { width: CONTENT_W, lineGap: 3 });
    doc.text(q.question, MARGIN, y, { width: CONTENT_W, lineGap: 3 });
    y += qTextH + 8;

    // Options
    if (q.options) {
      for (let i = 0; i < q.options.length; i++) {
        const label = String.fromCharCode(65 + i);
        const optText = `${label})  ${q.options[i]}`;
        doc.fontSize(9.5).font(FONT_REGULAR).fillColor('#44403c');
        doc.text(optText, MARGIN + 18, y, { width: CONTENT_W - 18, lineGap: 2 });
        y += 14;
      }
      y += 6;
    } else {
      // NAT answer box
      doc.rect(MARGIN + 15, y, CONTENT_W - 30, 32).stroke('#d97706').lineWidth(0.8);
      doc.fontSize(9).font(FONT_ITALIC).fillColor('#a8a29e').text('Answer: ________________________', MARGIN + 20, y + 10, { width: CONTENT_W - 30 });
      y += 44;
    }

    // Separator
    doc.moveTo(MARGIN, y).lineTo(PAGE_W - MARGIN, y).stroke('#e7e5e4');
    y += 14;

    if (y > PAGE_H - 70) {
      footer();
      newPage();
      header(`${sectionTitle} (continued)`);
      y = 50;
    }
  }

  footer();
}

// ── Answer Key ─────────────────────────────────────────────────────────────
function renderAnswerKey(questions: Question[]) {
  newPage();
  header('Answer Key');

  doc.fontSize(16).font(FONT_BOLD).fillColor('#1c1917').text('Answer Key', MARGIN, 50, { align: 'center' });
  drawLine(MARGIN, 70, PAGE_W - MARGIN, 70, '#e7e5e4');
  doc.fontSize(9).font(FONT_ITALIC).fillColor('#78716c').text('Verify your answers after completing the full paper.', MARGIN, 75, { align: 'center' });

  let y = 95;
  const perRow = 3;
  const rowH = 22;
  const colW = CONTENT_W / perRow;

  for (let i = 0; i < questions.length; i += perRow) {
    const row = questions.slice(i, i + perRow);
    for (let j = 0; j < row.length; j++) {
      const q = row[j];
      const qNum = q.id.split('_q')[1];
      const answer = Array.isArray(q.answer) ? q.answer.join('') : q.answer;

      const x = MARGIN + j * colW;
      doc.fontSize(9).font(FONT_BOLD).fillColor('#d97706').text(`Q.${qNum}:`, x, y);
      doc.font(FONT_REGULAR).fillColor('#1c1917').text(answer, x + 35, y);
    }
    y += rowH;

    if (y > PAGE_H - 55) {
      footer();
      newPage();
      header('Answer Key (continued)');
      y = 50;
    }
  }

  footer();
}

// ── Solutions ──────────────────────────────────────────────────────────────
function renderSolutions(questions: Question[]) {
  newPage();
  header('Detailed Solutions');

  doc.fontSize(16).font(FONT_BOLD).fillColor('#1c1917').text('Detailed Solutions', MARGIN, 50, { align: 'center' });
  drawLine(MARGIN, 70, PAGE_W - MARGIN, 70, '#e7e5e4');

  let y = 80;

  for (const q of questions) {
    const qNum = q.id.split('_q')[1];

    // Question header
    doc.fontSize(10).font(FONT_BOLD).fillColor('#d97706').text(`Question ${qNum}`, MARGIN, y);
    doc.fontSize(8).font(FONT_ITALIC).fillColor('#78716c')
      .text(`[${q.subject} — ${q.topic}]`, MARGIN + 110, y);
    y += 14;

    // Short question text
    doc.fontSize(8).font(FONT_ITALIC).fillColor('#57534e');
    const shortQ = q.question.length > 110 ? q.question.substring(0, 110) + '...' : q.question;
    doc.text(shortQ, MARGIN, y, { width: CONTENT_W });
    y += doc.heightOfString(shortQ, { width: CONTENT_W }) + 6;

    // Answer
    doc.fontSize(9).font(FONT_BOLD).fillColor('#1c1917').text('Answer:', MARGIN, y);
    const ansText = Array.isArray(q.answer) ? `(${q.answer.join(', ')})` : `(${q.answer})`;
    doc.font(FONT_REGULAR).fillColor('#0d9488').text(ansText, MARGIN + 55, y);
    y += 14;

    // Solution
    doc.fontSize(9).font(FONT_REGULAR).fillColor('#44403c');
    const solLines = (q.solution || 'Solution not available.').split('\n');
    for (const line of solLines) {
      const lh = doc.heightOfString(line, { width: CONTENT_W - 15, lineGap: 2 });
      if (y + lh > PAGE_H - 55) {
        footer();
        newPage();
        header('Detailed Solutions (continued)');
        y = 50;
      }
      doc.text(line, MARGIN + 8, y, { width: CONTENT_W - 15, lineGap: 2 });
      y += lh + 2;
    }

    y += 12;
    doc.moveTo(MARGIN, y).lineTo(PAGE_W - MARGIN, y).stroke('#e7e5e4');
    y += 14;

    if (y > PAGE_H - 65) {
      footer();
      newPage();
      header('Detailed Solutions (continued)');
      y = 50;
    }
  }

  footer();
}

// ── Main PDF Generator ─────────────────────────────────────────────────────
export function generatePDF(branchCode: string, mockNum: number, questions: Question[], meta: PaperMetadata): string {
  const branch = BRANCHES.find(b => b.code === branchCode);
  const filename = `EduNeuro_${branch?.examCode || branchCode.toUpperCase()}_Mock_${String(mockNum).padStart(2, '0')}.pdf`;
  const outDir = path.join(ROOT, branchCode.toUpperCase(), `mock_${String(mockNum).padStart(2, '0')}`);
  fs.mkdirSync(outDir, { recursive: true });
  const filepath = path.join(outDir, filename);

  doc = new PDFDocument({ size: 'A4', margin: MARGIN });
  const stream = fs.createWriteStream(filepath);
  doc.pipe(stream);

  pageNum = 0;
  globalQNum = 0;

  // Cover
  renderCover(meta);

  // Instructions
  renderInstructions();

  // Section A — MCQ (first 35 questions)
  const mcqQuestions = questions.filter(q => q.type === 'mcq').slice(0, 35);
  renderQuestions('Section A — Multiple Choice Questions (MCQ)', mcqQuestions, 'mcq');

  // Section B — MSQ
  const msqQuestions = questions.filter(q => q.type === 'msq').slice(0, 5);
  renderQuestions('Section B — Multiple Select Questions (MSQ)', msqQuestions, 'msq');

  // Section C — NAT
  const natQuestions = questions.filter(q => q.type === 'nat').slice(0, 20);
  renderQuestions('Section C — Numerical Answer Type (NAT)', natQuestions, 'nat');

  // Answer Key
  renderAnswerKey(questions);

  // Solutions
  renderSolutions(questions);

  doc.end();

  return new Promise((resolve, reject) => {
    stream.on('finish', () => resolve(filepath));
    stream.on('error', reject);
  });
}

// ── Metadata Generator ─────────────────────────────────────────────────────
export function generateMetadata(branchCode: string, mockNum: number, questions: Question[]): PaperMetadata {
  const branch = BRANCHES.find(b => b.code === branchCode);
  const subjects = [...new Set(questions.map(q => q.subject))];
  const easy = questions.filter(q => q.difficulty === 'easy').length;
  const moderate = questions.filter(q => q.difficulty === 'moderate').length;
  const hard = questions.filter(q => q.difficulty === 'hard').length;

  return {
    platform: 'EduNeuro',
    branch: branchCode,
    branch_code: branch?.examCode || branchCode.toUpperCase(),
    branch_name: branch?.name || branchCode,
    mock_number: mockNum,
    title: `${branch?.name || branchCode} — Mock Test ${String(mockNum).padStart(2, '0')}`,
    type: 'premium_full_length_mock',
    generation_basis: 'previous_year_question_analysis',
    question_count: questions.length,
    maximum_marks: questions.reduce((sum, q) => sum + q.marks, 0),
    duration_minutes: 180,
    subjects,
    difficulty_distribution: {
      easy: Math.round((easy / questions.length) * 100),
      moderate: Math.round((moderate / questions.length) * 100),
      hard: Math.round((hard / questions.length) * 100),
    },
    created_at: new Date().toISOString(),
    created_for: 'EduNeuro Premium',
  };
}
