/**
 * GET /api/formulas
 *
 * Returns formula sheets with optional filters.
 */

import { NextResponse } from "next/server";

const FORMULA_SHEETS = [
  {
    id: "cs-ds-graph",
    branchCode: "CS",
    branchName: "Computer Science & IT",
    title: "Graph Algorithms",
    subject: "Algorithms",
    topic: "Graph Algorithms",
    formulas: [
      "Dijkstra: O((V + E) log V) with priority queue",
      "Bellman-Ford: O(VE) — handles negative edges",
      "Floyd-Warshall: O(V³) — all pairs shortest paths",
      "Prim's MST: O(E log V) with min-heap",
      "Kruskal's MST: O(E log E) with DSU",
      "DFS: O(V + E)",
      "BFS: O(V + E)",
      "Topological Sort: O(V + E)",
    ],
    notes: "Graph algorithms form ~15% of GATE CSE algorithms questions. Master time complexities.",
    isPremium: false,
    difficulty: "medium",
  },
  {
    id: "cs-toc-automata",
    branchCode: "CS",
    branchName: "Computer Science & IT",
    title: "Finite Automata & Regular Languages",
    subject: "Theory of Computation",
    topic: "Automata",
    formulas: [
      "NFA → DFA: Subset construction",
      "DFA minimization: Hopcroft's O(n log n)",
      "Pumping Lemma: L = {aⁿbⁿ | n ≥ 0} is not regular",
      "Closure properties: Union, concat, star, complement",
    ],
    notes: "TOC is high-yield. Regular languages, CFLs, and decidability appear every year.",
    isPremium: false,
    difficulty: "medium",
  },
  {
    id: "cs-os-deadlock",
    branchCode: "CS",
    branchName: "Computer Science & IT",
    title: "Deadlock Handling",
    subject: "Operating Systems",
    topic: "Deadlocks",
    formulas: [
      "Deadlock conditions: Mutual Exclusion, Hold & Wait, No Preemption, Circular Wait",
      "Banker's Algorithm: Safe sequence check",
      "Resource Allocation Graph: Claim edge, Assignment edge",
      "Prevention: Break one of four conditions",
      "Avoidance: Banker's algorithm with safety check",
    ],
    notes: "Deadlocks is a favorite GATE topic. Know all four conditions and handling methods.",
    isPremium: false,
    difficulty: "easy",
  },
  {
    id: "cs-dbms-sql",
    branchCode: "CS",
    branchName: "Computer Science & IT",
    title: "SQL & Relational Algebra",
    subject: "Database Management",
    topic: "SQL",
    formulas: [
      "σ (Selection): σ_{age>25}(Employee)",
      "π (Projection): π_{name, salary}(Employee)",
      "ρ (Rename): ρ_{E}(Employee)",
      "⋈ (Join): Employee ⋈_{dept_id=id} Department",
      "∪, ∩, − : Set operations",
      "Aggregate: γ_{dept, avg(salary)}(Employee)",
    ],
    notes: "Relational algebra and SQL are tested every year. Know the operators and their properties.",
    isPremium: true,
    difficulty: "easy",
  },
  {
    id: "ec-signal-fft",
    branchCode: "EC",
    branchName: "Electronics & Communication",
    title: "Signals & Systems — FFT",
    subject: "Signals and Systems",
    topic: "FFT",
    formulas: [
      "DFT: X(k) = Σ x(n) e^(-j2πkn/N)",
      "IDFT: x(n) = (1/N) Σ X(k) e^(j2πkn/N)",
      "FFT (radix-2): O(N log N)",
      "DIT FFT: Decimation in Time",
      "DIF FFT: Decimation in Frequency",
      "Linear vs Circular Convolution",
      "Zero-padding: N+M-1 for linear convolution",
    ],
    notes: "Signals & Systems carries 8-10 marks in GATE EC. Focus on FFT, convolution, and Laplace.",
    isPremium: true,
    difficulty: "hard",
  },
  {
    id: "ee-power-system",
    branchCode: "EE",
    branchName: "Electrical Engineering",
    title: "Power System Analysis",
    subject: "Power Systems",
    topic: "Load Flow",
    formulas: [
      "Per unit: X_pu = X_actual / X_base",
      "Newton-Raphson: Fast convergence, O(n²) per iteration",
      "Gauss-Seidel: Simple but slow convergence",
      "Power Flow: P = VI* cos(δ)",
      "Reactive Power: Q = VI* sin(δ)",
    ],
    notes: "Power systems is the largest section in EE. Master load flow methods.",
    isPremium: true,
    difficulty: "hard",
  },
  {
    id: "cs-math-probability",
    branchCode: "CS",
    branchName: "Computer Science & IT",
    title: "Probability & Statistics",
    subject: "Engineering Mathematics",
    topic: "Probability",
    formulas: [
      "Bayes' Theorem: P(A|B) = P(B|A)P(A) / P(B)",
      "Binomial: P(X=k) = C(n,k) p^k (1-p)^(n-k)",
      "Poisson: P(X=k) = (λ^k e^-λ) / k!",
      "Normal Distribution: N(μ, σ²)",
      "Expected Value: E[X] = Σ x P(x)",
      "Variance: Var(X) = E[X²] - (E[X])²",
    ],
    notes: "Probability carries 5-8 marks in every GATE paper. High ROI topic.",
    isPremium: false,
    difficulty: "medium",
  },
  {
    id: "me-thermodynamics",
    branchCode: "ME",
    branchName: "Mechanical Engineering",
    title: "Thermodynamics — Key Formulas",
    subject: "Thermodynamics",
    topic: "Laws of Thermodynamics",
    formulas: [
      "1st Law: ΔU = Q - W",
      "2nd Law: η = 1 - (T_c/T_h)",
      "Carnot Efficiency: Maximum possible efficiency",
      "Entropy: ΔS = ∫dQ_rev/T",
      "Enthalpy: H = U + PV",
      "Gibbs Free Energy: G = H - TS",
    ],
    notes: "Thermodynamics is the foundation of ME. Know all laws and their applications.",
    isPremium: true,
    difficulty: "hard",
  },
  {
    id: "cs-ds-tree",
    branchCode: "CS",
    branchName: "Computer Science & IT",
    title: "Trees & BST",
    subject: "Algorithms",
    topic: "Trees",
    formulas: [
      "BST: O(log n) search/insert/delete (average)",
      "AVL Rotation: LL, LR, RL, RR — balance factor |h(L) - h(R)| ≤ 1",
      "B-Tree: Order m → each node has ≤ m-1 keys, ≥ ceil(m/2)-1 keys",
      "Red-Black: 5 properties, O(log n) operations",
      "Segment Tree: O(log n) range queries, O(n) build",
      "Fenwick Tree: O(log n) point update, prefix sum",
    ],
    notes: "Trees are foundational. BST, AVL, B-trees are frequently tested.",
    isPremium: false,
    difficulty: "medium",
  },
  {
    id: "cs-dbms-normalization",
    branchCode: "CS",
    branchName: "Computer Science & IT",
    title: "Normalization & Keys",
    subject: "Database Management",
    topic: "Normalization",
    formulas: [
      "1NF: Atomic values, no repeating groups",
      "2NF: No partial dependency (remove from 1NF)",
      "3NF: No transitive dependency (non-key → non-key)",
      "BCNF: For every FD X→Y, X is a superkey",
      "Candidate Key: Minimal superkey",
      "Superkey: Any superset of a candidate key",
    ],
    notes: "Normalization is tested every year. Focus on identifying candidate keys.",
    isPremium: false,
    difficulty: "easy",
  },
  {
    id: "ec-network",
    branchCode: "EC",
    branchName: "Electronics & Communication",
    title: "Network Theory",
    subject: "Network Analysis",
    topic: "Network Theorems",
    formulas: [
      "KCL: ΣI_in = ΣI_out at any node",
      "KVL: ΣV around any loop = 0",
      "Thevenin: V_th, R_th (open-circuit voltage, equivalent resistance)",
      "Norton: I_n = V_th/R_th, R_n = R_th",
      "Superposition: Linear circuits only",
      "Maximum Power Transfer: R_L = R_th",
    ],
    notes: "Network theorems are basics but appear in every GATE EC paper.",
    isPremium: false,
    difficulty: "easy",
  },
  {
    id: "ee-machines",
    branchCode: "EE",
    branchName: "Electrical Engineering",
    title: "Electrical Machines",
    subject: "Electrical Machines",
    topic: "Transformers & Motors",
    formulas: [
      "Turns Ratio: N1/N2 = V1/V2",
      "Transformer Eq: V1/N1 = V2/N2 = E/N = 4.44fΦm",
      "Efficiency: η = Output / Input = Output / (Output + Losses)",
      "DC Motor Torque: T = (P×φ×Z×Ia) / (2π×A)",
      "Slip: s = (Ns - N) / Ns",
      "Synchronous Speed: Ns = 120f/P",
    ],
    notes: "Machines carries 12-15 marks in EE. Transformer and DC machines are high-yield.",
    isPremium: true,
    difficulty: "medium",
  },
  {
    id: "me-strength",
    branchCode: "ME",
    branchName: "Mechanical Engineering",
    title: "Strength of Materials",
    subject: "Mechanics of Materials",
    topic: "Stress & Strain",
    formulas: [
      "Stress: σ = P/A (normal), τ = P/A (shear)",
      "Strain: ε = δ/L (normal), γ = δ/L (shear)",
      "Hooke's Law: σ = E·ε, τ = G·γ",
      "Poisson's Ratio: ν = lateral strain / axial strain",
      "Bending: σ = My/I, σ_max = M·c/I",
      "Torsion: τ = Tr/J = (16T)/(πd³)",
    ],
    notes: "SOM is the #1 topic in ME. Stress, strain, bending, and torsion are tested every year.",
    isPremium: true,
    difficulty: "medium",
  },
  {
    id: "ce-soil-mechanics",
    branchCode: "CE",
    branchName: "Civil Engineering",
    title: "Soil Mechanics",
    subject: "Geotechnical Engineering",
    topic: "Soil Properties",
    formulas: [
      "Water Content: w = (Mw/Ms) × 100%",
      "Void Ratio: e = Vv/Vs",
      "Porosity: n = Vv/V = e/(1+e)",
      "Degree of Saturation: Sr = Vw/Vv",
      "Dry Density: ρd = ρ/(1+w)",
      "Relative Density: Dr = (emax - e) / (emax - emin)",
    ],
    notes: "Soil mechanics is the largest section in GATE CE. Master index properties.",
    isPremium: true,
    difficulty: "medium",
  },
  {
    id: "cs-aptitude",
    branchCode: "CS",
    branchName: "Computer Science & IT",
    title: "Quantitative Aptitude",
    subject: "General Aptitude",
    topic: "Quantitative",
    formulas: [
      "Percentage: (part/whole) × 100",
      "Profit/Loss: SP - CP, Profit% = Profit/CP × 100",
      "Time & Work: Work = Rate × Time, 1/R_total = Σ(1/R_i)",
      "Speed: Speed = Distance/Time, Relative Speed (same dir) = |S1-S2|",
      "Simple Interest: SI = (P×R×T)/100",
      "Compound Interest: CI = P(1+R/100)^T - P",
    ],
    notes: "Aptitude carries 15 marks in every paper. Easy marks — don't skip.",
    isPremium: false,
    difficulty: "easy",
  },
  {
    id: "ec-control-systems",
    branchCode: "EC",
    branchName: "Electronics & Communication",
    title: "Control Systems",
    subject: "Control Systems",
    topic: "Basics",
    formulas: [
      "Transfer Function: G(s) = C(s)/R(s) for zero IC",
      "Error: E(s) = R(s) - C(s)",
      "Steady State Error: ess = lim(s→0) s·E(s)",
      "Root Locus: Angle condition and Magnitude condition",
      "Nyquist: N = Z - P, where N = encirclements",
      "Bode: 20log|G(jω)| magnitude plot",
    ],
    notes: "Control systems carries 8-10 marks in EC. Root locus and stability are key.",
    isPremium: true,
    difficulty: "medium",
  },
  {
    id: "ee-engineering-math",
    branchCode: "EE",
    branchName: "Electrical Engineering",
    title: "Engineering Mathematics",
    subject: "Engineering Mathematics",
    topic: "Linear Algebra",
    formulas: [
      "Rank: Number of linearly independent rows/columns",
      "Eigenvalues: det(A - λI) = 0",
      "Eigenvectors: (A - λI)x = 0",
      "Cayley-Hamilton: Every matrix satisfies its own characteristic equation",
      "Matrix Inversion: A⁻¹ = adj(A) / det(A)",
      "Probability: P(A∪B) = P(A) + P(B) - P(A∩B)",
    ],
    notes: "Mathematics carries 13-15 marks in every branch paper. Easy scoring.",
    isPremium: false,
    difficulty: "medium",
  },
  {
    id: "me-fluid-mechanics",
    branchCode: "ME",
    branchName: "Mechanical Engineering",
    title: "Fluid Mechanics",
    subject: "Fluid Mechanics",
    topic: "Basics",
    formulas: [
      "Bernoulli: P/ρg + V²/2g + z = constant",
      "Continuity: A₁V₁ = A₂V₂ (incompressible)",
      "Manning's: V = (1/n)R^(2/3)S^(1/2)",
      "Darcy-Weisbach: hf = f(L/D)(V²/2g)",
      "Reynolds: Re = ρVD/μ",
      "Viscosity: μ = τ / (du/dy) — Newton's law of viscosity",
    ],
    notes: "Fluid mechanics carries 10-12 marks. Bernoulli and continuity are must-know.",
    isPremium: true,
    difficulty: "medium",
  },
  {
    id: "ce-structural-analysis",
    branchCode: "CE",
    branchName: "Civil Engineering",
    title: "Structural Analysis",
    subject: "Structural Engineering",
    topic: "Determinate Structures",
    formulas: [
      "Bending Moment: BM = wL²/8 (simply supported, UDL)",
      "Shear Force: SF_max = wL/2",
      "Deflection: δ = PL³/(48EI) (SS, center load)",
      "Macaulay's: EI d²y/dx² = M(x)",
      "Influence Line: Draw for reaction, shear, moment",
      "Strain Energy: U = ∫(M²/2EI)dx",
    ],
    notes: "Structural analysis is core to CE. Bending moment and deflection are frequently tested.",
    isPremium: true,
    difficulty: "hard",
  },
  {
    id: "ec-digital-logic",
    branchCode: "EC",
    branchName: "Electronics & Communication",
    title: "Digital Logic",
    subject: "Digital Logic",
    topic: "Combinational & Sequential",
    formulas: [
      "K-map: 4-variable → 16 cells, Gray code order",
      "Quine-McCluskey: Prime implicants → essential → minimal SOP/POS",
      "JK Flip-Flop: J=K=1 → toggle, eliminates SR invalid state",
      "T Flip-Flop: T=1 → toggle",
      "Counter Mod-N: Needs ⌈log₂N⌉ flip-flops",
      "Max frequency: f_max = 1/(t_pLH + t_pHL)",
    ],
    notes: "Digital logic is 6-8 marks in EC. K-map minimization and counters are frequent.",
    isPremium: false,
    difficulty: "easy",
  },
  {
    id: "in-process-control",
    branchCode: "IN",
    branchName: "Instrumentation Engineering",
    title: "Process Control",
    subject: "Control Systems",
    topic: "Process Control",
    formulas: [
      "PID: u(t) = Kp·e(t) + Ki·∫e(t)dt + Kd·de(t)/dt",
      "Steady State Error: Type 0/1/2 system responses",
      "Tuning: Ziegler-Nichols method",
      "Bode Plot: crossover frequency, phase margin, gain margin",
      "Root Locus: Asymptotes at angles (2q+1)180/(n-m)",
      "State Space: ẋ = Ax + Bu, y = Cx + Du",
    ],
    notes: "Process control is core to IN. PID tuning and stability criteria are high-yield.",
    isPremium: true,
    difficulty: "medium",
  },
  {
    id: "cs-compiler-design",
    branchCode: "CS",
    branchName: "Computer Science & IT",
    title: "Compiler Design",
    subject: "Compiler Design",
    topic: "Parsing",
    formulas: [
      "CLR(1): Canonical LR(1) — most powerful, most tables",
      "LR(1): LALR(1) merges same cores → smaller tables",
      "SLR(1): Uses FOLLOW sets for reduce items",
      "Operator Precedence: three relations — <·, ·=, ·>",
      "First/Follow: Essential for LL(1) and LR parsers",
      "Left Recursion: A → Aα | β must be eliminated",
    ],
    notes: "Compiler design is 6-8 marks in CSE. Parsing table construction is the most tested topic.",
    isPremium: false,
    difficulty: "medium",
  },
  {
    id: "ec-communication-systems",
    branchCode: "EC",
    branchName: "Electronics & Communication",
    title: "Communication Systems",
    subject: "Communications",
    topic: "Analog & Digital",
    formulas: [
      "Nyquist: C = 2B log₂M (noiseless)",
      "Shannon-Hartley: C = B log₂(1 + S/N)",
      "SNR (dB): 10 log₁₀(S/N)",
      "ASK/FSK/PSK: Bandwidth ≈ 2×bit rate",
      "QAM: M-ary signaling → log₂M bits/symbol",
      "Entropy: H = -Σ p(x) log₂ p(x)",
    ],
    notes: "Communication systems carries 10-12 marks in EC. Nyquist and Shannon theorems are must-know.",
    isPremium: true,
    difficulty: "medium",
  },
  {
    id: "me-manufacturing",
    branchCode: "ME",
    branchName: "Mechanical Engineering",
    title: "Manufacturing Processes",
    subject: "Manufacturing",
    topic: "Casting & Welding",
    formulas: [
      "Casting: Chvorinov's Rule: t_s = C(V/A)ⁿ",
      "Solidification Time: proportional to (Volume)²/(Surface Area)",
      "Welding: Heat input = (V×I)/(v) in J/mm",
      "Resistance Welding: Q = I²Rt",
      "Arc Welding: I = V/R, electrode melting rate",
      "Gating Ratio: 1:4:2 (sprue:runner:ingate)",
    ],
    notes: "Manufacturing carries 10-12 marks in ME. Casting and welding are frequently tested.",
    isPremium: true,
    difficulty: "easy",
  },
  {
    id: "cs-computer-networks",
    branchCode: "CS",
    branchName: "Computer Science & IT",
    title: "Computer Networks",
    subject: "Computer Networks",
    topic: "TCP/IP & Routing",
    formulas: [
      "Subnetting: 2^(h) addresses per subnet, h = host bits",
      "Class A: 1.0.0.0–126.0.0.0, /8",
      "Class B: 128.0.0.0–191.255.0.0, /16",
      "Class C: 192.0.0.0–223.255.255.0, /24",
      "TCP Window: Throughput = Window/RTT",
      "Utilization: a = Tt / (Tt + Ta) for Stop-and-Wait",
    ],
    notes: "Networks carries 8-10 marks in CSE. Subnetting and TCP/IP are high-yield.",
    isPremium: false,
    difficulty: "easy",
  },
  {
    id: "ec-edc",
    branchCode: "EC",
    branchName: "Electronics & Communication",
    title: "Electronic Devices & Circuits",
    subject: "EDC",
    topic: "Diodes & Transistors",
    formulas: [
      "PN Junction: I = I₀(e^(V/nV_T) - 1)",
      "Diode Clipping: Reference voltage determines clipping level",
      "BJT: I_C = βI_B, I_E = (1+β)I_B",
      "MOSFET: I_D = μ Cox (W/L) ((V_gs - V_th)V_ds - V_ds²/2)",
      "Zener Diode: Voltage regulation in reverse breakdown",
      "Half-wave rectifier: V_dc = V_m/π, Full-wave: V_dc = 2V_m/π",
    ],
    notes: "EDC carries 8-10 marks in EC. Diodes, BJT, and MOSFET are core topics.",
    isPremium: true,
    difficulty: "medium",
  },
  {
    id: "pi-industrial",
    branchCode: "PI",
    branchName: "Production and Industrial Engineering",
    title: "Industrial Engineering",
    subject: "Industrial Engineering",
    topic: "Basics",
    formulas: [
      "Break-even: BEQ = FC / (SP - VC)",
      "PERT/CPM: ES, EF, LS, LF, Slack = LS-ES",
      "Inventory: EOQ = √(2DS/H)",
      "Queueing: L = λW (Little's Law)",
      "Linear Programming: Maximize Z = cᵀx, subject to Ax ≤ b",
      "Sequencing: Johnson's rule for 2-machine n-job",
    ],
    notes: "Industrial engineering carries 10-12 marks. Production planning and inventory are key.",
    isPremium: true,
    difficulty: "medium",
  },
  {
    id: "ch-process",
    branchCode: "CH",
    branchName: "Chemical Engineering",
    title: "Process Calculations",
    subject: "Process Calculation",
    topic: "Material & Energy Balance",
    formulas: [
      "Material Balance: Input = Output + Accumulation",
      "Recycle: Fresh feed = (1-R) × (Feed to separator)",
      "Bypass: True stream = Bypass / (1 - bypass fraction)",
      "Energy Balance: ΣH_in = ΣH_out (SSOT)",
      "Humidity: H = (P_w / (P - P_w)) × (18/29)",
      "Relative Humidity: RH = P_w / P_sat × 100%",
    ],
    notes: "Process calculations is the foundation of CH. Material and energy balance are always tested.",
    isPremium: true,
    difficulty: "medium",
  },
  {
    id: "bt-biotech",
    branchCode: "BT",
    branchName: "Biotechnology",
    title: "Biotechnology — Core Concepts",
    subject: "Biotechnology",
    topic: "Basics",
    formulas: [
      "Enzyme Kinetics: Michaelis-Menten: V = V_max[S]/(K_m+[S])",
      "Monod Growth: μ = μ_max × S/(K_s+S)",
      "DNA: A=T, G=C (Chargaff's rule)",
      "PCR: Denaturation 94°C → Annealing 55°C → Extension 72°C",
      "Protein Synthesis: DNA →(transcription)→ RNA →(translation)→ Protein",
      "CRISPR: Cas9 + guide RNA → targeted DNA cleavage",
    ],
    notes: "Biotechnology is emerging. Enzymes, genetics, and molecular bio are tested.",
    isPremium: false,
    difficulty: "medium",
  },
  {
    id: "mt-metallurgy",
    branchCode: "MT",
    branchName: "Metallurgical Engineering",
    title: "Metallurgy — Key Concepts",
    subject: "Metallurgical Engineering",
    topic: "Basics",
    formulas: [
      "Phase Rule: F = C - P + 2 (Gibbs)",
      "Lever Rule: (C₀ - C_α) / (C_β - C₀)",
      "Crystal Structure: FCC 4 atoms/cell, BCC 2 atoms/cell, HCP 6 atoms/cell",
      "Hardness: Brinell HB = 2P/(πD(D-√(D²-d²)))",
      "Corrosion: Rate = (W×8760)/(ρ×A×t) mm/year",
      "Hume-Rothery: Similar atomic radii, crystal structure, electronegativity",
    ],
    notes: "Metallurgy basics: phase diagrams, crystal structures, and corrosion are high-yield.",
    isPremium: false,
    difficulty: "medium",
  },
  {
    id: "xe-engineering-sciences",
    branchCode: "XE",
    branchName: "Engineering Sciences",
    title: "Engineering Mathematics (XE)",
    subject: "Engineering Mathematics",
    topic: "Basics",
    formulas: [
      "Linear Algebra: Rank, eigenvalues, eigenvectors",
      "Calculus: Mean Value Theorem, Taylor Series",
      "Vector Calc: Div, Grad, Curl",
      "ODE: First order exact, 2nd order homogeneous",
      "Laplace: L{f(t)} = ∫₀^∞ f(t)e^(-st)dt",
      "Complex Analysis: Cauchy-Riemann equations",
    ],
    notes: "Engineering mathematics is common for XE paper. ~15 marks.",
    isPremium: false,
    difficulty: "medium",
  },
  {
    id: "xl-life-sciences",
    branchCode: "XL",
    branchName: "Life Sciences",
    title: "Life Sciences — Chemistry",
    subject: "Chemistry (XL)",
    topic: "Basics",
    formulas: [
      "Nernst: E = E° - (RT/nF)lnQ",
      "pH: pH = -log[H⁺], pOH = -log[OH⁻]",
      "Kinetics: Rate = k[A]^m[B]^n",
      "Arrhenius: k = A·e^(-Ea/RT)",
      "Adsorption: Langmuir θ = KP/(1+KP)",
      "Electrochemistry: Faraday's laws: m = Z·I·t",
    ],
    notes: "Chemistry in XL paper: electrochemistry, kinetics, and equilibrium.",
    isPremium: false,
    difficulty: "medium",
  },
  {
    id: "tf-textile",
    branchCode: "TF",
    branchName: "Textile Engineering & Fibre Science",
    title: "Textile Engineering",
    subject: "Textile Engineering",
    topic: "Basics",
    formulas: [
      "Crimp%: (L_straight - L_crimped)/L_straight × 100",
      "Twist: TPI = spindle speed / delivery speed",
      "Count: Ne = (840 × weight in lbs) / length in yards",
      "Breaking Length: L = Load / Linear density",
      "Tensile Strength: TS = Maximum load / Cross-sectional area",
      "Mixing: Optimal blend ratios for cost and properties",
    ],
    notes: "Textile engineering basics: yarn manufacturing, fiber properties, and testing.",
    isPremium: false,
    difficulty: "medium",
  },
  {
    id: "pe-petroleum",
    branchCode: "PE",
    branchName: "Petroleum Engineering",
    title: "Petroleum Engineering",
    subject: "Petroleum Engineering",
    topic: "Basics",
    formulas: [
      "Darcy: q = (kAΔP)/(μL)",
      "Reservoir Volume: OOIP = (7758 × A × h × φ × (1 - Sw)) / Boi",
      "Productivity Index: PI = q / (P_res - P_wf)",
      "Gas: pV = ZnRT (real gas)",
      "Gas Viscosity: Lee-Gonzalez-Eakin correlation",
      "Material Balance: F = Np(Bo + (Rp - Rsi)Rs) + WpBw",
    ],
    notes: "Petroleum engineering: reservoir characterization, well testing, and production.",
    isPremium: true,
    difficulty: "hard",
  },
  {
    id: "ey-ecology",
    branchCode: "EY",
    branchName: "Ecology & Environment",
    title: "Ecology & Environment",
    subject: "Ecology and Evolution",
    topic: "Basics",
    formulas: [
      "Population Growth: dN/dt = rN(1 - N/K)",
      "Species Diversity: H = -Σ pi ln(pi)",
      "NDVI: (NIR - Red) / (NIR + Red)",
      "Carbon Footprint: CF = Activity × Emission Factor",
      "Bioaccumulation: BCF = C_organism / C_water",
      "Energy Flow: 10% rule — only ~10% transfers to next trophic level",
    ],
    notes: "Ecology basics: population ecology, biodiversity, and environmental assessment.",
    isPremium: false,
    difficulty: "easy",
  },
  {
    id: "ma-mathematics",
    branchCode: "MA",
    branchName: "Mathematics",
    title: "Advanced Mathematics",
    subject: "Mathematics",
    topic: "Analysis & Algebra",
    formulas: [
      "Linear Algebra: Rank(A) = # linearly independent rows",
      "Eigenvalues: det(A - λI) = 0, trace = Σλ",
      "ODE: Characteristic equation for constant coefficient",
      "Complex Analysis: Cauchy theorem, Residue theorem",
      "Real Analysis: Bolzano-Weierstrass, Uniform continuity",
      "Group Theory: Lagrange: |G| = |H| × [G:H]",
    ],
    notes: "Mathematics MA paper: real analysis, algebra, and ODE are core.",
    isPremium: true,
    difficulty: "hard",
  },
  {
    id: "ph-physics",
    branchCode: "PH",
    branchName: "Physics",
    title: "Physics — Key Formulas",
    subject: "Physics",
    topic: "Mechanics & EM",
    formulas: [
      "Classical Mechanics: F = ma, KE = ½mv², PE = mgh",
      "SHM: x = A cos(ωt + φ), T = 2π/ω",
      "EM: Gauss ∮E·dA = Q/ε₀, Ampere ∮B·dl = μ₀I",
      "Maxwell: ∇×E = -∂B/∂t",
      "Optics: n = c/v, Snell: n₁sinθ₁ = n₂sinθ₂",
      "Quantum: E = hf, de Broglie λ = h/p",
    ],
    notes: "Physics paper: classical mechanics, EM, and quantum are most tested.",
    isPremium: true,
    difficulty: "hard",
  },
  {
    id: "ar-architecture",
    branchCode: "AR",
    branchName: "Architecture & Planning",
    title: "Architecture & Planning",
    subject: "Architecture",
    topic: "Design & Planning",
    formulas: [
      "Building Ratio: FAR = Total built-up / Plot area",
      "Setbacks: Minimum as per NBC/local building bye-laws",
      "Parking: 1 ECS per 50-100 sqm depending on building type",
      "Accessibility: Ramp slope ≤ 1:12",
      "Stair: Rise 150-180mm, Tread 250-300mm, 2R+T = 600±50mm",
      "Ventilation: Window area ≥ 1/10 of floor area",
    ],
    notes: "Architecture: building bye-laws, planning principles, and design basics.",
    isPremium: false,
    difficulty: "easy",
  },
  {
    id: "ag-agricultural",
    branchCode: "AG",
    branchName: "Agricultural Engineering",
    title: "Agricultural Engineering",
    subject: "Agricultural Engineering",
    topic: "Basics",
    formulas: [
      "Field Capacity: FC = (Eff_Width × Speed) / 8.34",
      "Spray: GPA = (5940 × GPM) / (MPH × W)",
      "Pump Power: P = (Q × H × ρ × g) / η",
      "Psychrometrics: RH = (P_v / P_sat) × 100",
      "Solar: I = I₀ × (1 + 0.033cos(360n/365))",
      "Evapotranspiration: ET₀ by Penman-Monteith",
    ],
    notes: "Agricultural engineering: farm machinery, irrigation, and post-harvest.",
    isPremium: false,
    difficulty: "medium",
  },
  {
    id: "gg-geomatics",
    branchCode: "GG",
    branchName: "Geomatics",
    title: "Geomatics",
    subject: "Geomatics",
    topic: "Surveying & GIS",
    formulas: [
      "Distance: D = (f × S) / f' (tacheometry)",
      "Elevation: BM + BS - FS = Elevation",
      "Correction: Chaining: C_e = L × (α × D) / 63360",
      "Correction: Temperature: C_t = α × L × (T_m - T_s)",
      "Leveling: RL = BS + (HI - FS)",
      "GIS: Area from coordinates (Shoelace formula)",
    ],
    notes: "Geomatics: surveying basics, adjustments, and GIS fundamentals.",
    isPremium: false,
    difficulty: "medium",
  },
];

export async function GET(request: Request) {
  try {
    const url = new URL(request.url);
    const branch = url.searchParams.get("branch");
    const search = url.searchParams.get("search")?.toLowerCase() || "";
    const isPremiumParam = url.searchParams.get("premium");

    let sheets = FORMULA_SHEETS;

    if (branch) {
      sheets = sheets.filter((s) => s.branchCode === branch.toUpperCase());
    }

    if (search) {
      sheets = sheets.filter(
        (s) =>
          s.title.toLowerCase().includes(search) ||
          s.subject.toLowerCase().includes(search) ||
          s.topic.toLowerCase().includes(search) ||
          s.formulas.some((f) => f.toLowerCase().includes(search))
      );
    }

    if (isPremiumParam === "true") {
      sheets = sheets.filter((s) => s.isPremium);
    }

    return NextResponse.json({ sheets, total: sheets.length });
  } catch (error) {
    console.error("[Formulas] Error:", error);
    return NextResponse.json({ sheets: [], total: 0 });
  }
}
