/**
 * Processed PYQ data loader — reads from `data/pyq/processed/*.json`.
 *
 * This module provides question data for ALL 20 GATE branches by loading
 * the pre-processed JSON files. These files are generated by the PYQ
 * extraction pipeline and contain full question data for each branch.
 */

import { readFileSync, existsSync, readdirSync } from "fs";
import { join } from "path";

const PROCESSED_DIR = join(process.cwd(), "..", "data", "pyq", "processed");

export interface ProcessedQuestion {
  id: string;
  question_number: number;
  question_text: string;
  subject: string;
  topic: string;
  options: string[];
  answer: string | null;
  question_type: string;
  marks: number;
  negative_marks: number;
  branch: string;
  year: number;
  session: string;
  difficulty: string;
  tags: string[];
  explanation: string;
  source: string;
  source_file: string;
}

export interface ProcessedBranchData {
  branch: string;
  totalQuestions: number;
  yearRange: { min: number; max: number };
  sessions: string[];
  generatedAt: string;
  questions: ProcessedQuestion[];
}

const branchCache = new Map<string, ProcessedBranchData>();

/**
 * Load processed question data for a specific branch.
 * Returns null if no processed data exists for that branch.
 */
export function getProcessedBranchData(branchCode: string): ProcessedBranchData | null {
  const code = branchCode.toUpperCase();

  if (branchCache.has(code)) {
    return branchCache.get(code)!;
  }

  const filePath = join(PROCESSED_DIR, `${code}.json`);
  if (!existsSync(filePath)) {
    return null;
  }

  try {
    const raw = readFileSync(filePath, "utf-8");
    const data = JSON.parse(raw) as ProcessedBranchData;
    branchCache.set(code, data);
    return data;
  } catch {
    return null;
  }
}

/**
 * Get all branch codes that have processed data available.
 */
export function getAvailableProcessedBranches(): string[] {
  if (!existsSync(PROCESSED_DIR)) return [];

  try {
    return readdirSync(PROCESSED_DIR)
      .filter((f) => f.endsWith(".json") && f !== "index.json")
      .map((f) => f.replace(/\.json$/, ""));
  } catch {
    return [];
  }
}

/**
 * Convert processed question format to PYQ API format.
 */
export function toPYQApiFormat(q: ProcessedQuestion): {
  id: string;
  questionId: string;
  questionNumber: number;
  subjectName: string;
  topicName: string;
  questionType: string;
  marks: number;
  questionText: string;
  options: string[];
  correctAnswer: string;
  answerExplanation: string;
  difficulty: string;
  year: number;
  session?: string;
  source?: { primary: string };
  answerVerified: boolean;
} {
  return {
    id: q.id,
    questionId: q.id,
    questionNumber: q.question_number,
    subjectName: q.subject,
    topicName: q.topic,
    questionType: q.question_type,
    marks: q.marks,
    questionText: q.question_text,
    options: q.options,
    correctAnswer: q.answer || "",
    answerExplanation: q.explanation || "",
    difficulty: q.difficulty,
    year: q.year,
    session: q.session,
    source: { primary: q.source || "GATE Official Question Paper" },
    answerVerified: q.answer !== null && q.answer !== "",
  };
}
