import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

interface Question {
  id: string;
  number: number;
  question: string;
  options: { A: string; B: string; C: string; D: string }[];
  correctAnswer: string[];
  marks: number;
  topic: string;
  explanation?: string;
}

interface PaperData {
  paperId: string;
  title: string;
  focus: string;
  totalQuestions: number;
  totalMarks: number;
  durationMinutes: number;
  generalAptitude: Question[];
  engineeringMathematics: Question[];
  technical: Question[];
}

const PAPERS_DIR = path.join(process.cwd(), "predicted-papers", "CS Predicted Papers");
const OUTPUT_DIR = path.join(process.cwd(), "public", "predicted-papers");

if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true });

const paperDirs = fs.readdirSync(PAPERS_DIR).filter((d) => fs.existsSync(path.join(PAPERS_DIR, d, "paper.json")));

for (const dir of paperDirs) {
  const paperPath = path.join(PAPERS_DIR, dir, "paper.json");
  const paper: PaperData = JSON.parse(fs.readFileSync(paperPath, "utf-8"));

  const outPath = path.join(OUTPUT_DIR, `${paper.paperId}.pdf`);
  const doc = new PDFDocument({ size: "A4", margins: { top: 50, bottom: 50, left: 50, right: 50 } });

  const stream = fs.createWriteStream(outPath);
  doc.pipe(stream);

  // Title page
  doc.fontSize(20).font("Helvetica-Bold").text("GATE CSE 2026", { align: "center" });
  doc.moveDown(0.3);
  doc.fontSize(14).text("Predicted Paper", { align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(16).text(paper.title, { align: "center" });
  doc.moveDown(0.3);
  doc.fontSize(11).font("Helvetica").text(`Focus: ${paper.focus}`, { align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(10).text(`Total Questions: ${paper.totalQuestions}  |  Total Marks: ${paper.totalMarks}  |  Duration: ${paper.durationMinutes} min`, { align: "center" });
  doc.moveDown(0.3);
  doc.fontSize(9).text("Generated by PadhaiShuru | padhaishuru.com", { align: "center" });

  // Questions
  const sections: { title: string; questions: Question[]; color: string }[] = [
    { title: "General Aptitude", questions: paper.generalAptitude, color: "#1e40af" },
    { title: "Engineering Mathematics", questions: paper.engineeringMathematics, color: "#7c3aed" },
    { title: "Technical (CSE)", questions: paper.technical, color: "#059669" },
  ];

  for (const section of sections) {
    doc.addPage();
    doc.fontSize(14).font("Helvetica-Bold").fillColor(section.color).text(section.title, { align: "center" });
    doc.moveDown(0.4);
    doc.font("Helvetica").fillColor("#000");

    for (const q of section.questions) {
      // Question
      doc.fontSize(10).font("Helvetica-Bold");
      const qText = `Q${q.number}. [${q.marks} mark${q.marks > 1 ? "s" : ""}] ${q.question}`;
      doc.text(qText, { width: 500 });

      // Options
      doc.font("Helvetica").fontSize(9);
      for (const [key, val] of Object.entries(q.options)) {
        const opt = String.fromCharCode(64 + parseInt(key)); // A, B, C, D
        doc.text(`${opt}. ${val}`, { indent: 20, width: 480 });
      }

      // Explanation (small, after options)
      if (q.explanation) {
        doc.font("Helvetica-Oblique").fontSize(8).fillColor("#374151");
        doc.text(`Explanation: ${q.explanation}`, { indent: 20, width: 480 });
        doc.fillColor("#000").font("Helvetica");
      }

      doc.moveDown(0.3);
    }
  }

  // Answer key page
  doc.addPage();
  doc.fontSize(16).font("Helvetica-Bold").text("Answer Key", { align: "center" });
  doc.moveDown(0.5);

  for (const section of sections) {
    doc.fontSize(12).font("Helvetica-Bold").fillColor(section.color).text(section.title);
    doc.moveDown(0.2);
    doc.font("Helvetica").fillColor("#000").fontSize(9);

    for (const q of section.questions) {
      const ans = q.correctAnswer.join(", ");
      doc.text(`Q${q.number}: ${ans}`, { indent: 10 });
    }
    doc.moveDown(0.4);
  }

  doc.end();

  stream.on("finish", () => {
    console.log(`Generated: ${outPath}`);
  });
}

console.log(`Generating ${paperDirs.length} PDFs...`);
