import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — EduNeuro",
  description:
    "EduNeuro privacy policy — how we handle your data, what we collect, and your rights.",
};

export default function PrivacyPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-16 md:py-24">
      <h1 className="font-serif text-3xl md:text-5xl leading-tight mb-4">
        Privacy Policy
      </h1>
      <p className="text-sm text-muted mb-12">
        Last updated: August 2026
      </p>

      <div className="space-y-12 text-sm text-foreground leading-relaxed">
        <section>
          <h2 className="font-serif text-xl mb-3">1. About EduNeuro</h2>
          <p>
            EduNeuro is an AI-powered, neuroscience-informed educational platform
            that helps students prepare for competitive examinations such as GATE
            through organised study resources, practice, progress tracking, and
            AI-assisted doubt resolution. This Privacy Policy explains what data
            we handle and why.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl mb-3">
            2. Google Sign-In and Information We Receive
          </h2>
          <p>
            EduNeuro uses{" "}
            <strong>Google OAuth (via Supabase Auth)</strong> as its sign-in
            method. When you click &ldquo;Continue with Google,&rdquo; Google
            shares a limited set of information with EduNeuro solely to create
            and authenticate your account:
          </p>
          <ul className="list-disc pl-6 mt-3 space-y-2">
            <li>Your Google email address</li>
            <li>Your full name</li>
            <li>Your Google account profile picture (avatar)</li>
          </ul>
          <p className="mt-3">
            EduNeuro does not request — and does not receive — access to your
            Google Drive, Gmail, contacts, calendar, or any other Google
            services beyond the basic identity profile listed above.
          </p>
          <p className="mt-3">
            This information is used only to populate your EduNeuro account
            (display name and avatar) and for authentication. You are not
            required to use Google Sign-In to use any free features of the
            platform.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl mb-3">
            3. Account and Profile Information
          </h2>
          <p>
            When you create an EduNeuro account, we store the following
            information in our database:
          </p>
          <ul className="list-disc pl-6 mt-3 space-y-2">
            <li>
              <strong>User ID</strong> — a unique identifier generated by
              Supabase Auth (not your Google ID directly)
            </li>
            <li>
              <strong>Username</strong> — a display name you choose during
              sign-up (visible to other users on leaderboards and chat)
            </li>
            <li>
              <strong>Email address</strong> — used for authentication and
              account-related communication
            </li>
            <li>
              <strong>Display name</strong> — derived from your Google profile
              name at sign-in
            </li>
            <li>
              <strong>Avatar URL</strong> — link to your Google profile picture
            </li>
            <li>
              <strong>Subscription tier</strong> — whether your account has
              active premium access
            </li>
          </ul>
          <p className="mt-3">
            Your username is publicly visible on leaderboards and in study chat.
            No other personal information is shared publicly by default.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl mb-3">
            4. Study Activity and Progress Data
          </h2>
          <p>
            EduNeuro tracks study-related activity to provide features such as
            verified study sessions, streaks, goals, and performance analytics.
            This includes:
          </p>
          <ul className="list-disc pl-6 mt-3 space-y-2">
            <li>
              Study session timestamps and durations (verified through
              page-visibility detection)
            </li>
            <li>
              Daily study goals and streak history
            </li>
            <li>
              Quiz and practice question responses and scores
            </li>
            <li>
              Library resource access patterns (which resources you have viewed
              or bookmarked)
            </li>
            <li>
              Leaderboard rankings based on verified study time
            </li>
          </ul>
          <p className="mt-3">
            This data is stored securely in our Supabase database. It is used
            solely to operate and improve the platform&apos;s features.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl mb-3">
            5. Payment and Subscription Information
          </h2>
          <p>
            EduNeuro uses <strong>Razorpay</strong> as its payment processor for
            subscriptions. Payment and billing details are handled entirely by
            Razorpay. EduNeuro does not store your full card or bank details.
          </p>
          <p className="mt-3">
            We receive and store limited subscription information from Razorpay:
          </p>
          <ul className="list-disc pl-6 mt-3 space-y-2">
            <li>
              Subscription status (active, expired, or cancelled)
            </li>
            <li>
              Subscription plan type
            </li>
            <li>
              Payment reference IDs (for support and dispute resolution)
            </li>
          </ul>
          <p className="mt-3">
            For full details on how Razorpay handles your payment information,
            please refer to the{" "}
            <a
              href="https://razorpay.com/privacy-policy/"
              target="_blank"
              rel="noopener noreferrer"
              className="underline"
            >
              Razorpay Privacy Policy
            </a>
            .
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl mb-3">
            6. AI Doubt Engine Data
          </h2>
          <p>
            EduNeuro&apos;s AI Doubt Engine allows you to ask questions about
            GATE subjects and receive AI-generated answers grounded in your
            study library. When you use this feature:
          </p>
          <ul className="list-disc pl-6 mt-3 space-y-2">
            <li>
              Your question text is sent to our AI provider (<strong>Groq</strong>)
              for processing
            </li>
            <li>
              Relevant context from your study library may be included in the
              request to produce accurate answers
            </li>
            <li>
              The AI-generated answer is returned and displayed to you in real
              time
            </li>
          </ul>
          <p className="mt-3">
            Doubt queries are processed dynamically and are not stored as
            persistent conversation history. However, usage of the AI feature may
            be logged for quality and improvement purposes. We do not use your
            doubt queries to train any AI models.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl mb-3">
            7. Global Study Chat
          </h2>
          <p>
            EduNeuro offers a real-time study chat for premium users. Messages
            you send in the chat are visible to other users and are stored in our
            database (via Supabase) while the chat session is active. Do not
            share personal or sensitive information in chat messages.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl mb-3">8. Data Storage</h2>
          <p>
            All EduNeuro user data — account profiles, study sessions, progress
            records, leaderboard entries, and chat messages — is stored using{" "}
            <strong>Supabase</strong>, a PostgreSQL-based cloud platform. Supabase
            provides encrypted data storage and transport. Our database
            configurations include Row Level Security (RLS) policies to enforce
            access controls at the database level.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl mb-3">
            9. Security Practices
          </h2>
          <p>
            EduNeuro takes the security of your data seriously. Measures we
            implement include:
          </p>
          <ul className="list-disc pl-6 mt-3 space-y-2">
            <li>
              Authentication via Supabase Auth with secure session management
            </li>
            <li>
              Database-level Row Level Security (RLS) policies
            </li>
            <li>
              HTTPS enforcement for all connections
            </li>
            <li>
              Service credentials stored as server-side environment variables
              and never exposed to clients
            </li>
            <li>
              Limited data collection — we only collect what is necessary to
              operate the platform
            </li>
          </ul>
          <p className="mt-3">
            No method of electronic storage or transmission is 100% secure. While
            we strive to protect your data, we cannot guarantee absolute security.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl mb-3">
            10. Third-Party Services
          </h2>
          <p>
            EduNeuro integrates with the following third-party services, each
            with its own privacy practices:
          </p>
          <ul className="list-disc pl-6 mt-3 space-y-2">
            <li>
              <strong>Supabase</strong> — authentication and database hosting
            </li>
            <li>
              <strong>Google</strong> — OAuth sign-in provider
            </li>
            <li>
              <strong>Groq</strong> — AI inference for the doubt engine
            </li>
            <li>
              <strong>Razorpay</strong> — payment processing
            </li>
            <li>
              <strong>Vercel</strong> — hosting and analytics
            </li>
          </ul>
          <p className="mt-3">
            We encourage you to review the privacy policies of these services.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl mb-3">
            11. Data Retention and Deletion
          </h2>
          <p>
            We retain your account data for as long as your account is active or
            as needed to provide the service. Study progress and session data are
            retained to maintain your learning history and streaks.
          </p>
          <p className="mt-3">
            If you wish to delete your account and all associated data, please
            contact us at{" "}
            <a
              href="mailto:sumantabhargab@gmail.com"
              className="underline"
            >
              sumantabhargab@gmail.com
            </a>
            . Account deletion will remove your profile, study data, and
            associated records from our systems.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl mb-3">12. Your Rights</h2>
          <p>
            You have the right to:
          </p>
          <ul className="list-disc pl-6 mt-3 space-y-2">
            <li>Access the personal data we hold about you</li>
            <li>Request correction of inaccurate data</li>
            <li>Request deletion of your account and data</li>
            <li>Withdraw consent for data processing where applicable</li>
            <li>
              Disconnect Google Sign-In from your EduNeuro account at any time
              through your Google Account settings
            </li>
          </ul>
          <p className="mt-3">
            To exercise any of these rights, please contact{" "}
            <a
              href="mailto:sumantabhargab@gmail.com"
              className="underline"
            >
              sumantabhargab@gmail.com
            </a>
            .
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl mb-3">13. Children&apos;s Privacy</h2>
          <p>
            EduNeuro is intended for students and adult learners. We do not
            knowingly collect personal information from children under the age of
            13. If you believe a child has provided us with personal information,
            please contact us so we can take appropriate action.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl mb-3">14. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. Changes will be
            posted on this page with an updated &ldquo;Last updated&rdquo; date.
            Continued use of the platform after changes constitutes acceptance of
            the updated policy.
          </p>
        </section>

        <section>
          <h2 className="font-serif text-xl mb-3">15. Contact</h2>
          <p>
            For any questions, concerns, or requests related to this Privacy
            Policy or your personal data, please reach out at{" "}
            <a
              href="mailto:sumantabhargab@gmail.com"
              className="underline"
            >
              sumantabhargab@gmail.com
            </a>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
